# Generated by Django 3.0.8 on 2020-07-06 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostgreSQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=20, unique=True, validators=[django.core.validators.validate_ipv4_address])),
                ('backup_method', models.CharField(choices=[('postgres', 'postgres'), ('rsync', 'rsync')], max_length=20)),
                ('retention', models.PositiveIntegerField(blank=True, null=True)),
                ('retention_policy', models.CharField(choices=[('DAYS', 'DAYS'), ('WEEKS', 'WEEKS'), ('MONTHS', 'MONTHS')], help_text='days, weeks or months', max_length=20)),
                ('key_pub', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
