# Generated by Django 3.0.8 on 2020-07-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgresql',
            options={'verbose_name_plural': 'PostgreSQL'},
        ),
    ]
