# Generated by Django 3.0.8 on 2020-07-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0002_auto_20200706_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgresql',
            name='key_pub',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
