# Generated by Django 3.1.4 on 2020-12-12 02:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0003_auto_20200706_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='config', max_length=100, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
