# Generated by Django 3.1.4 on 2020-12-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barman', '0004_diagnose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='data',
            field=models.JSONField(),
        ),
    ]
