version: '3.7'

services:

  web:
    restart: always
    image: python:3.7-buster
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - static_volume:/usr/src/mammoth/barman/static
      - .:/usr/src/mammoth

    command: gunicorn mammoth.wsgi:application --chdir /usr/src/mammoth --bind 0.0.0.0:8000 --reload
    expose:
      - 8000
    environment:
      - SECRET_KEY=02t&3r1uc5gnxt@##3qne9zq)m1k)--8ix7e&hns9ss20+l5dq
      - SQL_HOST=db
    restart: always
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:10
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/pgsql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=mammoth
      - POSTGRES_PASSWORD=mammoth
      - POSTGRES_DB=mammoth
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/mammoth/barman/static
    ports:
      - 80:80
    hostname: mammoth.local
    links:
      - web
    depends_on:
      - web
    dns:
      - 127.0.0.1
    dns_search: localhost

volumes:
  static_volume:
  postgres_data:
