[barman]
barman_user = barman
barman_home = /var/lib/barman
configuration_files_directory = /etc/barman.d/
log_file = /var/log/barman/barman.log
log_level = INFO
archiver = on
compression = custom
custom_compression_filter = pigz -c
custom_decompression_filter = pigz -c -d
retention_policy_mode = auto
basebackup_retry_times = 5
basebackup_retry_sleep = 60
reuse_backup = link