[db]
conninfo = host=db user=barman password=mammoth dbname=postgres
backup_method = rsync
ssh_command = ssh postgres@db
slot_name = barman
retention_policy =  RECOVERY WINDOW OF 3 DAYS
wal_retention_policy = main